### ISSUE TITLE
Duplicate entity id?

### ISSUE THREAD

**Issue by jaz000** [ZombieEnderman5/Ghostly#3]
I get this a lot

I think it depends what other mods with Mobs I have loaded - But I just got it again the moment I added DrZhark's Mo Creatures.

I appreciate there's at least 2 possible fixes for a duplicate id! But any thoughts on how to get past this?

thanks

[16:26:40] [Server thread/ERROR] [FML]: Encountered an exception while constructing entity 'ghostly:mutated_horse'
java.lang.reflect.InvocationTargetException: null
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method) ~[?:1.8.0_201]
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_201]
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(Unknown Source) ~[?:1.8.0_201]
	at java.lang.reflect.Constructor.newInstance(Unknown Source) ~[?:1.8.0_201]
	at net.minecraftforge.fml.common.registry.EntityEntryBuilder$ConstructorFactory.apply(EntityEntryBuilder.java:305) [EntityEntryBuilder$ConstructorFactory.class:?]
	at net.minecraftforge.fml.common.registry.EntityEntryBuilder$ConstructorFactory.apply(EntityEntryBuilder.java:291) [EntityEntryBuilder$ConstructorFactory.class:?]
	at net.minecraftforge.fml.common.registry.EntityEntry.newInstance(EntityEntry.java:68) [EntityEntry.class:?]
	at net.minecraft.world.biome.Biome$SpawnListEntry.newInstance(Biome.java:655) [anh$c.class:?]
	at sun.reflect.GeneratedMethodAccessor114.invoke(Unknown Source) ~[?:?]
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_201]
	at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_201]
	at net.optifine.reflect.Reflector.call(Reflector.java:967) [Reflector.class:?]
	at net.minecraft.world.WorldEntitySpawner.findChunksForSpawning(WorldEntitySpawner.java:214) [anb.class:?]
	at net.minecraft.world.WorldServer.tick(WorldServer.java:203) [oo.class:?]
	at net.optifine.override.WorldServerOF.tick(WorldServerOF.java:39) [WorldServerOF.class:?]
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:756) [MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668) [MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:252) [chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]
Caused by: java.lang.IllegalArgumentException: Duplicate id value for 16!
	at net.minecraft.network.datasync.EntityDataManager.register(EntityDataManager.java:113) ~[nb.class:?]
	at zombieenderman5.ghostly.common.entity.monster.EntityMutatedHorse.entityInit(EntityMutatedHorse.java:182) ~[EntityMutatedHorse.class:?]
	at net.minecraft.entity.Entity.<init>(Entity.java:217) ~[vg.class:?]
	at net.minecraft.entity.EntityLivingBase.<init>(EntityLivingBase.java:164) ~[vp.class:?]
	at net.minecraft.entity.EntityLiving.<init>(EntityLiving.java:120) ~[vq.class:?]
	at net.minecraft.entity.EntityCreature.<init>(SourceFile:21) ~[vx.class:?]
	at net.minecraft.entity.monster.EntityMob.<init>(EntityMob.java:26) ~[ade.class:?]
	at zombieenderman5.ghostly.common.entity.monster.EntityMutatedHorse.<init>(EntityMutatedHorse.java:90) ~[EntityMutatedHorse.class:?]
	... 20 more
[16:26:40] [Server thread/ERROR] [minecraft/MinecraftServer]: Encountered an unexpected exception
net.minecraft.util.ReportedException: Exception ticking world
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:762) ~[MinecraftServer.class:?]
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:668) ~[MinecraftServer.class:?]
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:252) ~[chd.class:?]
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:526) [MinecraftServer.class:?]
	at java.lang.Thread.run(Unknown Source) [?:1.8.0_201]
Caused by: java.lang.NullPointerException
	at net.minecraft.world.WorldEntitySpawner.findChunksForSpawning(WorldEntitySpawner.java:229) ~[anb.class:?]
	at net.minecraft.world.WorldServer.tick(WorldServer.java:203) ~[oo.class:?]
	at net.optifine.override.WorldServerOF.tick(WorldServerOF.java:39) ~[WorldServerOF.class:?]
	at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:756) ~[MinecraftServer.class:?]
	... 4 more

**Comment by jaz000** [comment]
In all honesty I think this is down to Mo Creatures - I found a few other bugs in that pack
